version: "1.0"
services:
  web:
    build:
      context: .
    container_name: chat-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task
    ports:
      - "8000:8080"
    depends_on:
      - db
    links:
      - redis
  db:
     image: postgres
     container_name: db
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=baxrom5593
      - POSTGRES_DB=task
     restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
