POST http://localhost:8080/chat/add
Content-Type:  application/json

{
  "name": "salom1111",
  "users": [1,3,3]
}

###
POST http://localhost:8080/chat/get
Content-Type: application/json

{
  "user": 2
}